// src/commands/mod.rs
pub mod awk;
pub mod base64_cmd;
pub mod basename;
pub mod cat;
pub mod cut;
pub mod cp;
pub mod curl;
pub mod diff_cmd;
pub mod dirname;
pub mod find;
pub mod grep;
pub mod gzip;
pub mod head;
pub mod jq;
pub mod join;
pub mod ls;
pub mod mkdir;
pub mod mv;
pub mod nl;
pub mod paste;
pub mod registry;
pub mod rm;
pub mod sed;
pub mod sort;
pub mod tail;
pub mod tar;
pub mod test_cmd;
pub mod touch;
pub mod tr;
pub mod wc;
pub mod uniq;
pub mod xargs;
pub mod types;
pub mod utils;
pub mod query_engine;
pub mod yq;

pub use registry::{CommandRegistry, register_batch_a, register_batch_b, register_batch_c, create_batch_a_registry, create_batch_ab_registry, create_batch_abc_registry};
pub use types::{Command, CommandContext, CommandResult};
